# ClusterAvailabilityLevel
# ClusterCpuOversubscription
# ClusterMemoryOversubscription
# CpuArchitecture
# CustomRamAnge
# DatabaseType
# DisasterRecoveryTenancy
# EncryptionState
# EsxHostCpuOversubscription
# EsxHostMemoryOversubscription
# EventCategory
# EventOrigin
# Eventource
# Eventtatus
# EventType
# HostState
# Hp3parTier
# IpAddressAllocationState
# IpAddressAllocationPurpose
# LamaTemplateState
# LamaTemplateStatus
# LicenseEventType
# LifecycleActionType
# LifecycleState
# LvmLevel
# LvmType
# MacAddressAllocationState
# MigrationState
# SapOffering
# ServiceLevel
# ServiceRole
# SidOrigin
# SidType
# StorageStatus
# StorageType
# StorageWorkloadType
# SubscriptionStatus
# Suitability
# Supplier
# TicketClosureCodeInterpretation
# TicketImplementationStatus
# TicketOrigin
# Tickettate
# TicketType
# Topology
# Virtualization
# VlanRole
# VlanType
# VolumeGroupType
# VolumeType
# WorkloadType
# Zone
# DataCenter
# Vcenter
# Tenant
# Cluster
# Hp3par
# Cpg
# CustomCpuValue
# Tier
# CustomSize
# Datastore
# EsxHost
# EventCode
# Lvm
# OrderTracking
# System
# TicketClosureCode
# Ticket
# Event
# Hp3parCapacity
# Hp3parPair
# OperatingSystem
# Image
# Size
# Vlan
# InstanceHost
# NicType
# IpAddressPool
# MacAddressPool
# InstanceHostNicConfig
# LamaTemplateTargetSidInstanceHost
# LamaTemplateTargetSidInstanceHostNicConfig
# LifecycleAction
# LamaTemplate
# LamaTemplateTargetSid
# ServiceRoleDetail
# LamaTemplateTargetSidService
# LamaTemplateTargetSidVolume
# Service
# Service_vip
# SidLvmLicenseEvent
# TenantUserGroup
# VlanTriplet
# Vla
# Vmnetwork
# VolumeGroup
# VolumeGroupFileSystem
# Volume
